config_pyiot:
  mqtt:
    server_url: "broker.mqttdashboard.com"
    server_port: 1883
    topic_sub: "eyrc/JePrMuRo/iot_to_ros"
    topic_pub: "eyrc/JePrMuRo/ros_to_iot"
    qos: 0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listed to this topic to receive data from MQTT Subscription

  google_apps:
    spread_sheet_id: AKfycbxEiPqTRyjrB27WG0utVSnA2a8VXsUjYi-XhE0tUhgeqNzy8nE # Spreadsheet Id/Webapp Id
    eyrc_spread_sheet_id: AKfycbw850dk4moVgebU2GGe0PUQUvvg8jTpSjBQCawJt3_13vgujLk #Eyrc spreadsheet
    